services:
  app:
    build: ./amt_crm_backend
    container_name: amt_crm_app
    restart: unless-stopped
    volumes:
      - app_storage:/var/www/storage
      - app_cache:/var/www/bootstrap/cache
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync
    env_file:
      - ./amt_crm_backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - amt_crm_shared_network
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "php-fpm", "|", "grep", "-v", "grep"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    security_opt:
      - no-new-privileges:true

  db:
    image: mysql:8.0
    container_name: amt_crm_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: amt_crm_user_password_2024
      MYSQL_DATABASE: amt_crm_backend
      MYSQL_USER: amt_crm_user
      MYSQL_PASSWORD: amt_crm_user_password_2024
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - db_data:/var/lib/mysql
      - ./amt_crm_db/init:/docker-entrypoint-initdb.d
    networks:
      - amt_crm_shared_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
    security_opt:
      - no-new-privileges:true

  nginx:
    build:
      context: ./amt_crm_backend
      dockerfile: Dockerfile.nginx
    container_name: amt_crm_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./amt_crm_nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
      - app_storage:/var/www/storage:ro
    networks:
      - amt_crm_shared_network
    depends_on:
      app:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true

volumes:
  db_data:
    driver: local
  app_storage:
    driver: local
  app_cache:
    driver: local
  nginx_logs:
    driver: local

networks:
  amt_crm_shared_network:
    external: true
    name: amt_crm_shared_network 