version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amt_crm_app
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      - ./public:/var/www/public
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - amt_crm_network

  db:
    image: mysql:8.0
    container_name: amt_crm_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: amt_crm_backend
      MYSQL_USER: amt_crm_user
      MYSQL_PASSWORD: amt_crm_user_password_2024
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - amt_crm_network

  nginx:
    image: nginx:alpine
    container_name: amt_crm_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./public:/var/www/public:ro
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - amt_crm_network

volumes:
  db_data:

networks:
  amt_crm_network:
    driver: bridge 