services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amt_crm_app
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      - ./public:/var/www/public
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - amt_crm_shared_network
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "php-fpm", "|", "grep", "-v", "grep"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  db:
    image: mysql:8.0
    container_name: amt_crm_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - amt_crm_shared_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  nginx:
    image: nginx:alpine
    container_name: amt_crm_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.combined.conf:/etc/nginx/nginx.conf
      - ./docker-entrypoint-nginx.sh:/docker-entrypoint-nginx.sh
    networks:
      - amt_crm_shared_network
    depends_on:
      - app
    command: ["/bin/sh", "-c", "mkdir -p /var/cache/nginx/client_temp && nginx -g 'daemon off;'"]

volumes:
  db_data:

networks:
  amt_crm_shared_network:
    external: true
    name: amt_crm_shared_network 