version: '3.8'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./infra/certs:/etc/nginx/certs:ro
      - ./infra/vhost.d:/etc/nginx/vhost.d
      - ./infra/html:/usr/share/nginx/html
    environment:
      - ENABLE_IPV6=true
    networks:
      - backend

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=himmanav11@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./infra/certs:/etc/nginx/certs:rw
      - ./infra/vhost.d:/etc/nginx/vhost.d
      - ./infra/html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
    networks:
      - backend

  app:
    build: .
    image: amt_crm_backend_app
    container_name: amt_crm_backend_app
    restart: always
    working_dir: /var/www
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - VIRTUAL_HOST=api.himmanav.com
      - LETSENCRYPT_HOST=api.himmanav.com
      - LETSENCRYPT_EMAIL=your-email@himmanav.com
    expose:
      - "80"
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql:8
    container_name: amt_crm_backend_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge 