version: '3.8'

services:
  app:
    build: .
    image: amt_crm_backend_app
    container_name: amt_crm_backend_app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql:8
    container_name: amt_crm_backend_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: amt_crm_backend_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge 