services:
  # Nginx Reverse Proxy (HTTP only for now)
  nginx-proxy:
    image: nginx:alpine
    container_name: amt_crm_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/logs:/var/log/nginx
      - ./public:/var/www/public:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - amt_crm_network

  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amt_crm_app
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      - ./public:/var/www/public
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - amt_crm_network
    healthcheck:
      test: ["CMD", "php", "artisan", "health:check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: amt_crm_db
    environment:
      MYSQL_ROOT_PASSWORD: "amt_crm_root_password_2024"
      MYSQL_DATABASE: amt_crm_backend
      MYSQL_USER: amt_crm_user
      MYSQL_PASSWORD: "amt_crm_user_password_2024"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - amt_crm_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pamt_crm_root_password_2024"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s



networks:
  amt_crm_network:
    driver: bridge 

volumes:
  mysql_data: 