---
- name: Backend Server Provisioning (Laravel + MySQL)
  hosts: backend
  become: yes
  vars:
    docker_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
    docker_apt_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    required_packages:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - ufw
      - nginx
      - certbot
      - python3-certbot-nginx

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required system packages
      apt:
        name: "{{ required_packages }}"
        state: present
        update_cache: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: "{{ docker_apt_key_url }}"
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "{{ docker_apt_repo }}"
        state: present
        filename: docker

    - name: Install Docker and Docker Compose
      apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: yes

    - name: Ensure Docker service is enabled and started
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Ensure Nginx is enabled and started
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Allow OpenSSH through UFW
      ufw:
        rule: allow
        name: OpenSSH

    - name: Allow Nginx Full profile through UFW (HTTP/HTTPS)
      ufw:
        rule: allow
        name: 'Nginx Full'

    - name: Enable UFW firewall
      ufw:
        state: enabled
        policy: deny
        direction: incoming
        logging: 'on'

    - name: Print completion message
      debug:
        msg: "Backend server is provisioned and ready for Laravel + MySQL Docker deployment."
