version: '3.8'

services:
  # Nginx Reverse Proxy (Standalone Container)
  nginx:
    image: nginx:alpine
    container_name: amt_crm_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx
      - laravel_public:/var/www/public:ro
      - laravel_storage:/var/www/storage:ro
    depends_on:
      laravel-app:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - amt_crm_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run

  # Laravel Application (External Service)
  laravel-app:
    image: amt-crm-backend:latest
    container_name: amt_crm_app
    volumes:
      - laravel_storage:/var/www/storage
      - laravel_cache:/var/www/bootstrap/cache
      - laravel_public:/var/www/public
      - laravel_logs:/var/www/storage/logs
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=host.docker.internal
      - PHP_OPCACHE_ENABLE=1
      - PHP_OPCACHE_MEMORY_CONSUMPTION=128
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=4000
    env_file:
      - ../laravel-backend/.env
    restart: unless-stopped
    networks:
      - amt_crm_network
    healthcheck:
      test: ["CMD", "php", "artisan", "health:check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    security_opt:
      - no-new-privileges:true
    user: "www:www"

networks:
  amt_crm_network:
    driver: bridge
    name: amt_crm_network
    external: true
    driver_opts:
      com.docker.network.bridge.name: amt_crm_network

volumes:
  laravel_storage:
    name: amt_crm_laravel_storage
    driver: local
  laravel_cache:
    name: amt_crm_laravel_cache
    driver: local
  laravel_public:
    name: amt_crm_laravel_public
    driver: local
  laravel_logs:
    name: amt_crm_laravel_logs
    driver: local 