# Frontend Docker Compose Template
# Copy this to your frontend repository and update as needed

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amt_crm_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://amt_crm_app:9000
    networks:
      - amt_crm_shared_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  amt_crm_shared_network:
    external: true
    name: amt_crm_shared_network 
    